<?php
/**
 * Open Source Social Network
 *
 * @package   (Informatikon.com).ossn
 * @author    OSSN Core Team <info@opensource-socialnetwork.org>
 * @copyright 2014 iNFORMATIKON TECHNOLOGIES
 * @license   General Public Licence http://www.opensource-socialnetwork.org/licence
 * @link      http://www.opensource-socialnetwork.org/licence
 * @translation Jeremy Monroe <info@kreativmind.co>
 */

$en = array(
	'home' => 'Bahay',
	'site:index' => 'Salubungin!',
	'news:feed' => 'Balita',
	'new:feed' => 'Balita',
	'photos:ossn' => 'Retrato',
	'admin:view:site' => 'Tingnan ang Site',
	
	'home:top:heading' => "Salubungin to %s! Sumali ngayon para magkaroon ng mga bagong kaibigan, lumikha ng mga grupo, magdagdag ng mga larawan, at marami pang iba.",
	'create:account' => 'Gumawa ng account',
	'its:free' => "Ito ay palaging magiging libre.",
	
	'register:ok:message' => "Ang iyong account ay naka-rehistro. Isang activation email ay naipadala na sa iyong mailbox. Kung hindi mo natanggap ang email, mangyaring suriin ang iyong spam / junk polder.",
	
	'copyright' => '&copy; COPYRIGHT',
	'powered' => 'Designed by KreativMind',
	
	'name' => 'Pangalan',
	'birthdate' => 'Araw ng kapanganakan',
	'first:name' => 'Unang Pangalan',
	'last:name' => 'Huling Pangalan',
	'email' => 'Email',
	'email:again' => 'Pumasok na mali e-mail',
	'username' => 'Username',
	'password' => 'Hudyat',
	'day' => 'Araw',
	'month' => 'Buwan',
	'year' => 'Taon',
	'male' => 'Lalaki',
	'female' => 'Babae',
	'account:create:notice' => 'Sa pamamagitan ng pag-click Lumikha ng isang account, sumasang-ayon ka sa aming',
	'gender' => 'Kasarian',
	
	'account:settings' => 'Account mga Setting',
	'page:error' => 'Hindi nahanap ang pahina!',
	'page:error:text' => 'Ang pahina na iyong hiniling ay hindi magagamit o maaaring natanggal.',
	'page:error:heading' => '404',
	
	'search:users' => 'Mag Tao',
	'admin:logout' => 'Log out',
	'logout' => 'Log out',
	
	'ossn:like:this' => '%s nagustuhan ito',
	'ossn:like:you:and:this' => 'Ikaw and %s nagustuhan ito',
	'ossn:like:people' => '%s Mga Tao',
	'ossn:like:person' => '%s Tao',
	'ossn:liked:you' => 'Ikaw nagustuhan ito',
	'ossn:unlike' => 'Hindi nagugustuhan',
	'ossn:like' => 'Gusto',
	
	'admin:components' => 'mga sangkap',
	'admin:dashboard' => 'Dashbord',
	'admin:install' => 'Installer',
	'admin:themes' => 'Tema',
	'admin:basic' => 'Batayan',
	'admin:cache' => 'Cache',
	'admin:mode' => 'Paraan',
	'configure' => 'Isaayos',
	'admin:help' => 'Tulong',
	'admin:support' => 'Makatulong',
	
	'ossn:update:check:error' => 'Pagkakamali',
	
	'upload' => 'Mag-upload',
	'save' => 'Iligtas',
	'add' => 'Magdagdag',
	'edit' => 'Mamatnugot',
	'search' => 'Paghahanap',
	'delete' => 'Alisin',
	
	'admin:users' => 'Listahan ng gumagamit',
	'admin:add:user' => 'Magdagdag ng user',
	'admin:user:deleted' => 'Tao ay tinanggal na!',
	'admin:user:delete:error' => 'Hindi matanggal ang tao. Mangyaring subukan muli sa ibang pagkakataon.',
	
	'type' => 'Uri',
	'normal' => 'Normal',
	'admin' => 'Administrador',
	
	'lastlogin' => 'Huling pagpasok',
	
	'my:version' => 'Aking OSSN Version',
	'online:users' => 'Mga Tao Online',
	'themes' => 'Tema',
	'users' => 'Mga Tao',
	'components' => 'Mga Bahagi',
	'available:updates' => 'Magagamit na mga update',
	'website:name' => 'Pangalan ng Website',
	'owner:email' => 'E-mail ng may-ari',
	'default:lang' => 'Default na wika',
	
	'timeline' => 'Timeline',
	'photos' => 'Retrato',
	'friends' => 'Kaibigan',
	'links' => 'Mga links',
	'ossn:add:user:mail:subject' => "%s mangyaring kumpirmahin ang iyong email address para sa %s!",
	'ossn:add:user:mail:body' => "Bago mo simulang gamitin ang %s, kailangan mong kumpirmahin ang iyong email address.

Mangyaring kumpirmahin ang iyong email address sa pamamagitan ng pag-click sa link sa ibaba:

%s


Maaari mong kopyahin at i-paste ang address sa iyong browser nang manu-mano sa kaso ang link ay hindi gumagana.

%s",
	'user:friends' => 'Kaibigan',
	'user:account:validated' => 'Account ay matagumpay na napatunayan!',
	'user:account:validate:fail' => 'Hindi mapatunayan account! Mangyaring subukan muli sa ibang pagkakataon',
	
	'cache:enabled' => 'Cache matagumpay na pinagana!',
	'cache:disabled' => 'Cache matagumpay na hindi pinagana!',
	'cache:enable' => 'Matagumpay Cache',
	'cache:disable' => 'Cache',
	
	'cache:1' => 'Pinagana',
	'cache:0' => 'Hindi Pinagana',
	'cache:notice' => '
Mga Tindahan ng CSS at Javascript file sa isang cache upang mapabuti ang pagganap ng site.',
	
	'theme:install:notice' => 'Mag-upload ng isang wastong package tema .zip.',
	'com:install:notice' => 'Mag-upload ng isang wastong component package .zip.',
	
	'login:error' => 'Di-wastong username o password!',
	'login:error:sub' => "Kami ay hindi maaaring mag-log in. Mangyaring suriin ang iyong username o password at subukan muli.",
	'login:success' => 'Ikaw ay naka-log in ngayon in!',
	'com:installed' => 'Component ay nai-upload sa iyong listahan ng mga bahagi, maaari mo na ngayong paganahin ang mga ito mula sa pahina ng mga sangkap.',
	'com:install:error' => 'Hindi makapag-upload component, tiyakin na ito ay isang wastong package.',
	'settings:saved' => 'Nai-save ang Mga Setting',
	'com:deleted' => 'Component na ito ay tinanggal!',
	'com:delete:error' => 'Hindi matanggal ang component! Mangyaring subukan muli sa ibang pagkakataon.',
	'com:disabled' => 'Matagumpay na hindi pinagana!',
	'com:enabled' => 'Pinagana component!',
	
	'theme:delete:active' => 'Hindi matanggal ang aktibong tema.',
	'theme:deleted' => 'Tema ay tinanggal na.',
	'theme:delete:error' => 'Hindi matanggal ang tema! Mangyaring subukan muli sa ibang pagkakataon.',
	'theme:enabled' => 'Tema ay matagumpay pinagana!',
	'theme:installed' => 'Tema ay matagumpay na nai-install!',
	'theme:install:error' => 'Hindi ma-install na tema. Tiyakin na ito ay tugma sa mga OSSN bersyon na iyong ginagamit.',
	
	'fields:require' => 'Lahat ng mga patlang ay kinakailangan!',
	'username:error' => 'Username ay hindi wasto.',
	'password:error' => 'Dapat na higit sa 5 mga letra Password.',
	'account:created' => 'Ang iyong account ay nagawa na.',
	'account:create:error:admin' => 'Nabigo ang pagpaparehistro ng account! Mangyaring subukan muli sa ibang pagkakataon.',
	'user:updated' => 'Na-update User!',
	'logged:out' => 'Ngayon Ikaw ay naka-log out!',
	'username:inuse' => 'Ang sumusunod na username ay nagamit na. Mangyaring pumili ng ibang username.',
	'email:inuse' => 'Ang email address na ginamit mo ay umiiral na sa aming database. Mangyaring subukan ang ibang email address.',
	'email:invalid' => 'Email address ay hindi wasto! Siguraduhin na ang email address na iyong ipinasok ay tama.',
	'email:error:matching' => "Mga email address ay hindi tumutugma.",
	'account:created:email' => "Ang iyong account ay na-rehistro! Kami ay nagpadala sa iyo ng isang activation email account. Kung hindi mo natanggap ang email, mangyaring suriin ang iyong spam / junk folder",
	
	'administration' => 'Pangangasiwa',
	
	'privacy' => 'Privacy',
	'close' => 'Isara',
	'open' => 'Buksan',
	'public' => 'Publiko',
	'friends' => 'Kaibigan',
	'privacy:public:note' => 'Lahat ng tao sa site na ito ay maaaring makita ang mga ito.',
	'privacy:friends:note' => 'Ang iyong kaibigan ay maaaring makita ito.',
	
	'add:friend' => 'Idagdag kaibigan',
	'cancel:request' => 'Kanselahin ang Kahilingan',
	'remove:friend' => 'Unfriend',
	'no:friends' => 'Walang mga Kaibigan',
	'settings' => 'Mga Setting',
	'ossn:add:friend:error' => 'Hindi maaaring magdagdag ng kaibigan!',
	'ossn:friend:request:submitted' => 'Ang iyong kahilingan na maging kaibigan ay naipadala na!',
	
	/* Upgrades */
	'upgrade:file:load:error' => 'Hindi ma-load upgrade file!',
	'upgrade:success' => "Ang iyong website ay matagumpay na na-upgrade na pakawalan %s.",
	'upgrade:failed' => "Hindi-upgrade ang iyong site upang i-release %s.",
	'upgrade:not:available' => 'Walang ipe-upgrade!!',
	
	'site:login' => 'Login',
	/* Page errors */
	'system:error:title' => 'May nangyaring mali!',
	'system:error:text' => 'May nangyaring mali! I-reload ang pahinang ito at subukan muli.',
	
	/* Password Reset */
	'reset:login' => 'I-reset ang Password',
	'reset:password' => 'I-reset ang iyong password',
	'enter:new:password' => 'Ipasok ang iyong bagong password sa ibaba at i-click ang i-reset.',
	'reset' => 'I-reset ang',
	'enter:emai:reset:pwd' => 'Ipasok ang email address ng iyong account upang i-reset ang password.',
	'ossn:reset:password:subject' => 'I-reset ang iyong password',
	'ossn:reset:password:body' => "Kamusta %s,
	
Please click the link below to reset password or copy the link and paste into your browser's address bar:

%s

%s",
	'passord:reset:success' => 'Matagumpay na nabago ang Password!',
	'passord:reset:fail' => 'Hindi-reset ng password! Mangyaring subukan muli sa ibang pagkakataon.',
	'password:reset:email:required' => 'Email Hindi maaaring walang laman!',
	'passord:reset:email:success' => 'Mga tagubilin reset Password ay ipapadala sa iyong email address.',
	'reset:password' => 'I-reset ang Password',
	
	'erros:reporting' => 'Pag-uulat ng Error',
	'erros:off' => 'Mula sa',
	'erros:on' => 'Sa',
	'basic:settings' => 'Mga Pangunahing Setting',
	
	'ossn:new:version:error' => 'Hindi kilala',
	'ossn:version:avaialbe' => "%s",
	
	'ossn:exception:title' => 'Isang system error ang naganap. Mangyaring subukan muli sa ibang pagkakataon. Maaari mong i-email ang mga detalye ng error sa sistema ng administrator sa %s.',
	'ossn:securitytoken:failed' => 'Ang aksyon na iyong hiniling ay hindi wasto.',
	'ossn:component:delete:exception' => 'Sigurado ka bang gusto mong tanggalin ang component na ito?',
	'ossn:user:delete:exception' => 'Sigurado ka bang gusto mong tanggalin ang user na ito?',
	
	//access
	'title:access:1' => 'Pribado',
	'title:access:2' => 'Publiko',
	'title:access:3' => 'Kaibigan',
	
	'upload:file:error:ini_size' => 'Ang file na sinubukan mong i-upload ay masyadong malaki.',
	'upload:file:error:form_size' => 'Ang file na sinubukan mong i-upload ay masyadong malaki.',
	'upload:file:error:partial' => 'Upload ang file ay hindi kumpleto.',
	'upload:file:error:no_file' => 'Walang file na napili.',
	'upload:file:error:no_tmp_dir' => 'Hindi mai-save ang na-upload na file..',
	'upload:file:error:cant_write' => 'Hindi mai-save ang na-upload na file..',
	'upload:file:error:extension' => 'Hindi mai-save ang na-upload na file..',
	'upload:file:error:unknown' => 'Nabigo ang pag-upload ng file.',
	
	'ossn:post:size:exceed' => 'Ang aksyon na iyong hiniling ay lumampas sa limitasyon ng laki.',
	
	'admin:components' => 'Components',
	'admin:themes' => 'Tema',
	'admin:com:installer' => 'I-install ang Component',
	'admin:theme:installer' => 'I-install ang Tema',
	'admin:cache:settings' => 'Mga Setting ng cache',
	'admin:add:user' => 'Magdagdag ng user',
	'admin:user:list' => 'Listahan ng mga gumagamit',
	'admin:edit:user' => 'I-edit ang User',
	'admin:login' => 'Login',
	'admin:notification:email' => 'Website notification sa e-mail',
	'notification_email' => 'Notification sa e-mail (noreply@domain.com)',
	'owner_email' => 'May-ari Email (mysite@domain.com)',
	'ossn:websitename' => 'Pangalan ng iyong website',
	'ossn:user:validation:resend' => 'Ang iyong account ay hindi napatunayan! Dapat mong patunayan ang iyong account bago mag-log in. Isa pang pagpapatunay na email ay ipinadala sa iyong email address.',
	'site:timepassed:text' => '%s ang nakalipas',
	// localization of passed time: 16 time elements (even = singular / odd = plural)
	'site:timepassed:data' => 'segundo|segundos|minuto|minutos|oras|oras|araw|araws|linggo|linggos|buwan|buwans|taon|taons|dekada|dekadas',
	'ossn:notification:no:notification' => 'Wala na ipakita',
	'admin:button:enable' => 'Paganahin',
	'admin:button:enabled' => 'Pinagana',
	'admin:button:disable' => 'Hindi pinagana',
	'admin:button:configure' => 'I-configure',
	'admin:button:delete' => 'Burahin',
	'admin:component:author' => 'May-akda',
	'admin:component:website' => 'Website',
	'admin:sidemenu:components' => 'Mga Bahagi',
	'admin:sidemenu:themes' => 'Temas',
	'admin:sidemenu:settings' => 'Mga Setting ng Site',
	'admin:sidemenu:usermanager' => 'Mga user manager',
	'cancel' => 'Kanselahin',
	'ossn:language:complete' => 'Kumpleto',
	'ossn:pagination:first' => 'Una',
	'ossn:pagination:last' => 'Wakas',
	'validate' => 'Patunayan',
	'admin:users:unvalidated' => 'Hindi wastong user',
	'admin:user:validated' => 'Wastong user',
	'admin:user:validate:error' => 'Hindi ma-validate ang user.',
	
	//v3.0
	//admin
	'my:files:version' => 'Aking mga File Version Ossn',
	'cache:flush:error' => 'Hindi flush cache, siguraduhin cache ay pinagana sa mga setting ng cache',
	'cache:flushed' => 'Matagumpay flushed Cache',
	'ossn:version' => 'OSSN version', 
	'php:extension' => 'PHP extension',
	'php:version' => 'PHP version',
	'php:function' => 'PHP tungkulin',
	'admin:old:com' => "Ang iyong ossn_com.xml file ay batay sa mga lumang bersyon ng Ossn. Paki-update '%s' component.",
	'admin:old:theme' => "Ang iyong ossn_theme.xml file ay batay sa mga lumang bersyon ng Ossn. Paki-update '%s' temas.",
	'admin:button:disabled' => 'Hindi pinagana',
	'admin:flush:cache' => 'Flush Cache',
	'admin:com:version' => 'Version',
	'admin:com:author' => 'May-akda',
	'admin:com:author:url' => 'May-akda URL',
	'admin:com:license' => 'Lisensya',
	'admin:com:requirements' => 'Kinakailangan',
	'admin:com:availability' => 'Pagiging',
	'ossn:exception:make:sure' => 'Sigurado ka ba?',
	
	/*
	 * List of ISO 639-1 language codes
	 * http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
	 */
	"aa" => "Afar",
	"ab" => "Abkhazian",
	"af" => "Afrikaans",
	"am" => "Amharic",
	"ar" => "Arabic",
	"as" => "Assamese",
	"ay" => "Aymara",
	"az" => "Azerbaijani",
	"ba" => "Bashkir",
	"be" => "Byelorussian",
	"bg" => "Bulgarian",
	"bh" => "Bihari",
	"bi" => "Bislama",
	"bn" => "Bengali; Bangla",
	"bo" => "Tibetan",
	"br" => "Breton",
	"ca" => "Catalan",
	"co" => "Corsican",
	"cs" => "Czech",
	"cy" => "Welsh",
	"da" => "Danish",
	"de" => "German",
	"dz" => "Bhutani",
	"el" => "Greek",
	"en" => "English",
	"eo" => "Esperanto",
	"es" => "Spanish",
	"et" => "Estonian",
	"eu" => "Basque",
	"fa" => "Persian",
	"fi" => "Finnish",
	"fj" => "Fiji",
	"fo" => "Faeroese",
	"fr" => "French",
	"fy" => "Frisian",
	"ga" => "Irish",
	"gd" => "Scots / Gaelic",
	"gl" => "Galician",
	"gn" => "Guarani",
	"gu" => "Gujarati",
	"he" => "Hebrew",
	"ha" => "Hausa",
	"hi" => "Hindi",
	"hr" => "Croatian",
	"hu" => "Hungarian",
	"hy" => "Armenian",
	"ia" => "Interlingua",
	"id" => "Indonesian",
	"ie" => "Interlingue",
	"ik" => "Inupiak",
	"is" => "Icelandic",
	"it" => "Italian",
	"iu" => "Inuktitut",
	"iw" => "Hebrew (obsolete)",
	"ja" => "Japanese",
	"ji" => "Yiddish (obsolete)",
	"jw" => "Javanese",
	"ka" => "Georgian",
	"kk" => "Kazakh",
	"kl" => "Greenlandic",
	"km" => "Cambodian",
	"kn" => "Kannada",
	"ko" => "Korean",
	"ks" => "Kashmiri",
	"ku" => "Kurdish",
	"ky" => "Kirghiz",
	"la" => "Latin",
	"ln" => "Lingala",
	"lo" => "Laothian",
	"lt" => "Lithuanian",
	"lv" => "Latvian/Lettish",
	"mg" => "Malagasy",
	"mi" => "Maori",
	"mk" => "Macedonian",
	"ml" => "Malayalam",
	"mn" => "Mongolian",
	"mo" => "Moldavian",
	"mr" => "Marathi",
	"ms" => "Malay",
	"mt" => "Maltese",
	"my" => "Burmese",
	"na" => "Nauru",
	"ne" => "Nepali",
	"nl" => "Dutch",
	"no" => "Norwegian",
	"oc" => "Occitan",
	"om" => "(Afan) Oromo",
	"or" => "Oriya",
	"pa" => "Punjabi",
	"pl" => "Polish",
	"ps" => "Pashto / Pushto",
	"pt" => "Portuguese",
	"qu" => "Quechua",
	"rm" => "Rhaeto-Romance",
	"rn" => "Kirundi",
	"ro" => "Romanian",
	"ru" => "Russian",
	"rw" => "Kinyarwanda",
	"sa" => "Sanskrit",
	"sd" => "Sindhi",
	"sg" => "Sangro",
	"sh" => "Serbo-Croatian",
	"si" => "Singhalese",
	"sk" => "Slovak",
	"sl" => "Slovenian",
	"sm" => "Samoan",
	"sn" => "Shona",
	"so" => "Somali",
	"sq" => "Albanian",
	"sr" => "Serbian",
	"ss" => "Siswati",
	"st" => "Sesotho",
	"su" => "Sundanese",
	"sv" => "Swedish",
	"sw" => "Swahili",
	"ta" => "Tamil",
	"te" => "Tegulu",
	"tg" => "Tajik",
	"th" => "Thai",
	"ti" => "Tigrinya",
	"tk" => "Turkmen",
	"tl" => "Tagalog",
	"tn" => "Setswana",
	"to" => "Tonga",
	"tr" => "Turkish",
	"ts" => "Tsonga",
	"tt" => "Tatar",
	"tw" => "Twi",
	"ug" => "Uigur",
	"uk" => "Ukrainian",
	"ur" => "Urdu",
	"uz" => "Uzbek",
	"vi" => "Vietnamese",
	"vo" => "Volapuk",
	"wo" => "Wolof",
	"xh" => "Xhosa",
	"yi" => "Yiddish",
	"yo" => "Yoruba",
	"za" => "Zuang",
	"zh" => "Chinese",
	"zu" => "Zulu"
);
ossn_register_languages('en', $en);
